const gulp = require('gulp');
const rename = require('gulp-rename');
const insert = require('gulp-insert');
const path = require('../config.json').path;

const warning = `
/**
 * STOP!
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * This file should be edited only in the reset-console.js and then is built
 * into the reset-console.txt file. See the README.md in the reset-console
 * folder for an explaination.
 **/`

gulp.task('reset-console', () => {
  gulp.src(path.RESET_CONSOLE_JS)
    .pipe(insert.prepend(warning))
    .pipe(rename('reset-console.txt'))
    .pipe(gulp.dest(path.RESET_CONSOLE))
})
